services:
  - type: web
    name: fastapi-app
    env: docker
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 8080
      - key: API_KEY
        sync: false
    healthCheckPath: /
    numInstances: 1